title: "Narno"
baseurl: https://narno.co/
description: "Quelques liens à propos de Narno."
author:
  name: Narno
  url: https://narno.com
language: fr
languages:
  - code: fr
    locale: fr_FR
    name: Français
avatar: avatar.png
image: avatar.png
source: https://github.com/ArnaudLigny/narno.co
theme:
  - pwa
  - netlify
  - netlify-cms
manifest:
  background_color: '#1E293B'
  theme_color: '#1E293B'
serviceworker:
  enabled: true
defaultpages:
  404:
    published: false
  sitemap:
    published: false
taxonomies:
  categories: disabled
  tags: disabled
pagination:
  enabled: false
virtualpages:
  # Apache Rewrite file
  - path: .htaccess
    output: apache_rewrite
output:
  formats:
    apache_rewrite:
      mediatype: 'text/plain'
      extension: ''
  pagetypeformats:
    homepage: html
netlify:
  redirects:
    - from: https://nrn.netlify.app/*
      to: https://narno.co/:splat
      status: 301
      force: true
