site:
  title: Narno.co
  baseline: Narno's URL shortener.
  baseurl: https://narno.co/
  description: Narno's URL shortener.
  language: en
  fmpages:
    index:
      permalink: /
      redirect: /r/
    redirects:
      layout: _redirects.txt
      permalink: _redirects
    admin:
      layout: admin/index.html
      title: 'Content Manager (Netlify CMS)'
  date:
    format: 'j F Y'
    timezone: 'Europe/Paris'
  netlify:
    cms:
      path: 'admin'
      version: 'latest'
    identity:
      version: 'v1'
