title: "Narno.co"
baseline: "Static URL shortener!"
baseurl: https://narno.co/
description: "Static URL Shortener, Custom Links & Link Management."
output:
  formats:
    - name: netlify_redirects
      mediatype: 'text/plain'
      extension: ''
virtualpages:
  - path: ""
    redirect: l
  - path: admin
    layout: admin/index
    title: "Content Manager (Netlify CMS)"
    output: html
  - path: _redirects
    output: netlify_redirects
date:
  format: 'j F Y'
  timezone: 'Europe/Paris'
netlify:
  cms:
    path: 'admin'
    version: 'latest'
  identity:
    version: 'v1'
