[build]
  command = "chmod +x netlify.sh && bash netlify.sh"
  publish = "_site"
  environment = { PHP_VERSION = "7.2" }

[context.deploy-preview]
  command = "chmod +x netlify.sh && bash netlify.sh $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "chmod +x netlify.sh && bash netlify.sh $DEPLOY_PRIME_URL"

[template.environment]
  CECIL_TITLE = "Title"
  CECIL_BASELINE = "Short description"
  CECIL_DESCRIPTION = "Full description"
