backend:
  name: git-gateway
  branch: master
media_folder: "static/images"
public_folder: "/images"
collections:
  - label: "Links"
    name: "l"
    identifier_field: slug
    folder: "content/l"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    fields:
      - {label: "Slug", name: "slug", widget: "string", required: true, hint: "Slug is used to create the link. ie: 'my-slug'."}
      - {label: "Target URL", name: "redirect", widget: "string", required: true}
      - {label: "Title", name: "title", widget: "string", hint: "(optionnal)"}
      - {label: "Date", name: "date", widget: "datetime", hint: "(optionnal)"}
  - label: "Settings"
    name: "settings"
    description: >
      Site settings.
    delete: false
    editor:
      preview: false
    files:
      - label: "Configuration"
        name: "config"
        file: "config.yml"
        fields:
          - {label: "Title", name: "title", widget: "string", default: "Narno.co", required: true}
          - {label: "Baseline", name: "baseline", widget: "string", default: "URL Shortener.", required: true}
          - {label: "Base URL", name: "baseurl", widget: "string", default: "/", required: true}
          - {label: "Description", name: "description", widget: "string", default: "URL Shortener.", required: true}
          - label: "Date"
            name: "date"
            widget: "object"
            fields:
              - {label: "Format", name: "format", widget: "string", default: "j F Y", required: true}
              - {label: "Time zone", name: "timezone", widget: "string", default: "Europe/Paris", required: true}
          - label: "Netlify"
            name: "netlify"
            widget: "object"
            fields:
              - label: "CMS"
                name: "cms"
                widget: "object"
                fields:
                  - {label: "Path", name: "path", widget: "string", default: "admin", required: true}
                  - {label: "Version", name: "version", widget: "string", default: "latest", required: true}
              - label: "Identity"
                name: "identity"
                widget: "object"
                fields:
                  - {label: "Version", name: "version", widget: "string", default: "v1", required: true}
