backend:
  name: git-gateway
  branch: master
media_folder: "static/images"
public_folder: "/images"
collections:
  - label: "URL"
    name: "r"
    folder: "content/r"
    create: true
    editor:
      preview: false
    fields:
      - {label: "Title", name: "title", widget: "string", hint: "Title is used to create the short URL. ie: 'My Title' become '/my-title'."}
      - {label: "URL", name: "redirect", widget: "string", required: true}
      - {label: "Date", name: "date", widget: "datetime", hint: "(optionnal)"}
  - label: "Settings"
    name: "settings"
    description: >
      Settings.
    delete: false
    editor:
      preview: false
    files:
      - label: "Configuration"
        name: "config"
        file: "cecil.yml"
        fields:
          - label: "Site"
            name: "site"
            widget: "object"
            fields:
              - {label: "Title", name: "title", widget: "string", default: "Narno.co", required: true}
              - {label: "Baseline", name: "baseline", widget: "string", default: "URL Shortener.", required: true}
              - {label: "Base URL", name: "baseurl", widget: "string", default: "/", required: true}
              - {label: "Description", name: "description", widget: "string", default: "URL Shortener.", required: true}
              - label: "Date"
                name: "date"
                widget: "object"
                fields:
                  - {label: "Format", name: "format", widget: "string", default: "j F Y", required: true}
                  - {label: "Time zone", name: "timezone", widget: "string", default: "Europe/Paris", required: true}
              - label: "Netlify"
                name: "netlify"
                widget: "object"
                fields:
                  - label: "CMS"
                    name: "cms"
                    widget: "object"
                    fields:
                      - {label: "Path", name: "path", widget: "string", default: "admin", required: true}
                      - {label: "Version", name: "version", widget: "string", default: "latest", required: true}
                  - label: "Identity"
                    name: "identity"
                    widget: "object"
                    fields:
                      - {label: "Version", name: "version", widget: "string", default: "v1", required: true}
